// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj1ytOLuh0z23Vid0pdiAuhKhMcWLHyac',
    appId: '1:795868681852:web:8d7432a94572f8214f5bf9',
    messagingSenderId: '795868681852',
    projectId: 'car-doctor-3ba16',
    authDomain: 'car-doctor-3ba16.firebaseapp.com',
    storageBucket: 'car-doctor-3ba16.appspot.com',
    measurementId: 'G-QYCLNBKDHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvh_tY5g_hHOk1_PQm6DdJCjixORi7uoE',
    appId: '1:795868681852:android:e5a9ee5b6b8be83a4f5bf9',
    messagingSenderId: '795868681852',
    projectId: 'car-doctor-3ba16',
    storageBucket: 'car-doctor-3ba16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBAEjwcsNAy6xge33MNbyEcqAWmwo11E',
    appId: '1:795868681852:ios:8b85adfa66cbc6834f5bf9',
    messagingSenderId: '795868681852',
    projectId: 'car-doctor-3ba16',
    storageBucket: 'car-doctor-3ba16.appspot.com',
    iosBundleId: 'com.doctor.car.carDoctor',
  );
}
